### ISSUE TITLE
Automatic Open Graph meta tags for posts

### ISSUE THREAD

**Issue by noraj** [ppoffice/hexo-theme-hueman#283]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

---

## Description

It would be nice to have the following Open Graph meta tags automatically generated for each article (post).

```html
<meta property="og:title" content="European Travel Destinations">
<meta property="og:description" content="Offering tour packages for individuals or groups.">
<meta property="og:image" content="http://euro-travel-example.com/thumbnail.jpg">
<meta property="og:url" content="http://euro-travel-example.com/index.htm">
<meta property="og:site_name" content="European Travel, Inc.">
```

- `og:title` from the title of the post
- (Optional) `og:description` like an excerpt from the X first chars of the post
- `og:image` from the thumbnail front-matter
- `og:url` from the post permanent URL
- `og:site_name` from the site `_config.yml` title

This is independent from https://github.com/ppoffice/hexo-theme-hueman/wiki/Miscellaneous#open-graph

**Comment by noraj** [comment]
It seems that it is already the case (Idk if it's hexo or the theme).

For this article https://rawsec.ml/en/archlinux-kalu/ I have

```html
<meta property="og:type" content="article">
<meta property="og:title" content="Kalu - Keeping ArchLinux Up-to-date">
<meta property="og:url" content="https://rawsec.ml/en/archlinux-kalu/index.html">
<meta property="og:site_name" content="Rawsec">
<meta property="og:description" content="Intro# Basically updating ArchLinux is as easy as running pacman -Syu. But blindly running pacman -Syu everyday is not necessarily a good idea. Sometimes some updates require manual intervention, so y">
<meta property="og:locale" content="en_US">
<meta property="og:image" content="https://rawsec.ml/images/archlinux.svg">
```
